[package]
name = "RustHash"
version = "0.0.2"
authors = ["Exo-poulpe <exo.poulpe@outlook.com>"]
edition = "2018"

[dependencies]
clap="*"
md-5="*"
sha-1="*"
sha2="*"
raw-cpuid="*"
sys-info="*"
time="*"
termcolor="*"
